# This is just sample code for a 2-button remote.

esphome:
  name: button_remote_1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Buttons
binary_sensor:
  # Button 1
  - platform: gpio
    pin:
      number: D5
      inverted: True
      mode: INPUT_PULLUP
    name: "Button 1"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - homeassistant.service:
            service: homeassistant.turn_on
            data:
              entity_id: light.office_light
  
  # Button 2
  - platform: gpio
    pin:
      number: D1
      inverted: True
      mode: INPUT_PULLUP
    name: "Button 2"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - homeassistant.service:
            service: homeassistant.turn_off
            data:
              entity_id: light.office_light
  
