# ##################################
# Sonoff S31
# ##################################
# GPIO0: button (inverted, input pullup)
# GPIO12: Relay and Red LED
# GPIO13: Blue LED
# ##################################
#
# This presents as a 'light' to Home Assistant

substitutions:
  # EXAMPLES - change these.
  device_name: livingroom_lamp
  friendly_name: Livingroom Lamp
 
esphome:
  name: $device_name

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Disable logging, since CSE7766 uses UART
logger:
  baud_rate: 0
  
# UART for CSE7766
uart:
  rx_pin: RX
  baud_rate: 4800

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Status LED - Blue LED
status_led: 
  pin:
    number: GPIO13   # Blue LED
    inverted: True


# Main button
binary_sensor:
  - platform: gpio
    name: ${friendly_name} Button
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    filters:
      # Debounce
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - light.toggle: main_light

# Main relay
output:
  - platform: gpio
    id: relay
    pin:
      number: GPIO12

# This presents as a light
light:
  - platform: binary
    name: $friendly_name
    output: relay
    id: main_light

# CSE7766 Power Sensor
sensor:
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Watts"
    update_interval: 10s
