# ##################################
# Sonoff S31
# ##################################
# GPIO0:  Button, inverted and pull-up
# GPIO12: relay and red LED
# GPIO13: Green LED
# ##################################

#
# THIS VERSION IS ONLY USED AS A WATTMETER
# THE RELAY IS INTERNAL SO NO SWITCH IS PRESENTED TO HA
# THIS IS DONE TO PREVENT 
#

substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name:  device_wattmeter
  friendly_name: Device Wattmeter

esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  # ENSURE THE RELAY IS ON AT BOOT
  on_boot:
    priority: 550.0
    then:
      - switch.turn_on: relay

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

status_led: 
  # https://esphome.io/components/status_led
  pin:
    number: GPIO13   # Green LED
    inverted: True


# REMOVE BUTTON - THIS IS A WATTMETER ONLY, NO POWER CONTROL
#binary_sensor:
#  - platform: gpio
#    # https://esphome.io/components/switch/gpio
#    name: ${friendly_name} Button
#    id: button
#    pin:
#      number: GPIO0
#      mode: INPUT_PULLUP
#      inverted: True
#    internal: True
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 10ms
#    on_press:
#      - switch.toggle: relay

# Unremark to view in HA as a switch
switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    name: $friendly_name
    # INTERNAL - Only a wattmeter
    internal: True

# Unremark to view in HA as a light
#light:
#  - platform: binary
#    name: $friendly_name
#    output: relay
#    id: main_light

# Power sensor
uart:
  rx_pin: RX
  baud_rate: 4800

# For wattmeter, this is all we care about
sensor:
  - platform: cse7766
    update_interval: 1s
    current:
      name: "$friendly_name Current"
    voltage:
      name: "$friendly_name Voltage"
    power:
      name: "$friendly_name Power"
