# ##############################################
# MOES IR BLASTER
# ##############################################
# GPIO4: Blue LED (inverted?)
# GPIO5: IR Receiver
# GPIO13:  Button
# GPIO14: IR LEDs Output (via NPN transistor)
# ##############################################

substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: living_room_ir
  friendly_name: Living Room IR Blaster
 
esphome:
  name: $device_name
#  platform: ESP8266
#  board: esp01_1m

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:
  services:
    - service: tv_on
      then:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E09966
      - delay: 200ms
      - remote_transmitter.transmit_samsung:
          data: 0xE0E09966
    - service: tv_off
      then:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E019E6
      - delay: 500ms
      - remote_transmitter.transmit_samsung:
          data: 0xE0E019E6
      - delay: 500ms
      - remote_transmitter.transmit_samsung:
          data: 0xE0E019E6
ota:

web_server:
  port: 80

logger:

remote_receiver:
  pin: 
    number: GPIO5
    inverted: True
    mode: INPUT_PULLUP
  dump: all
  idle: 25ms 

remote_transmitter:
  pin: GPIO14
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%
