# #############################################
# Martin Jerry 3-Way Dimmer STD01
# #############################################
# All functions are handled by the Tuya 
# module, which is a STC 15W408AS.
#
# Communication is via normal UART.
# GPIO3 - RX
# GPIO1 - TX
# 115,200 baud
#
# To flash via serial, must pull 
# pin 11 on the STC 15W408AS HIGH (VCC)
# which holds the chip in reset so it
# does not attempt serial comms to ESP.
# There is a pad next to pin 11 to solder to.
# #############################################

substitutions:
  device_name: 3way-mj-dimmer # change
  friendly_name: Martin Jerry 3way Dimmer # change
  icon: "mdi:light-switch"
  
esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  # Disable UART logging
  # UART used by Tuya module
  baud_rate: 0

uart:
  # For comms with Tuya module
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

# I like a web server.
web_server:
  port: 80

tuya:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

  - platform: uptime
    name: ${friendly_name} Uptime

binary_sensor:
  - platform: status
    name: ${friendly_name} Status

light:
  - platform: "tuya"
    name: ${friendly_name}
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 20
    max_value: 255
